export const largeAndSmall = [
  "US",
  "United Kingdom",
  "Italy",
  "Spain",
  "Finland",
  "Sweden",
  "US-Arizona",
  "US-Minnesota",
  "US-New York",
  "US-Washington",
  "US-Minnesota-Hennepin",
  "US-Arizona-Coconino",
  "US-Washington-Clark",
]

export const smallPlaces = [
  "Finland",
  "Sweden",
  "US-Arizona",
  "US-Minnesota",
  "US-Minnesota-Hennepin",
  "US-Arizona-Coconino",
  "US-Washington-Clark",
]

export const epicenters = [
  "US",
  "United Kingdom",
  "Italy",
  "Spain",
  "US-New York",
  "China",
]

export const usStates = [
  "US-Alabama",
  "US-Alaska",
  "US-Arizona",
  "US-Arkansas",
  "US-California",
  "US-Colorado",
  "US-Connecticut",
  "US-Delaware",
  "US-Florida",
  "US-Georgia",
  "US-Hawaii",
  "US-Idaho",
  "US-Illinois",
  "US-Indiana",
  "US-Iowa",
  "US-Kansas",
  "US-Kentucky",
  "US-Louisiana",
  "US-Maine",
  "US-Maryland",
  "US-Massachusetts",
  "US-Michigan",
  "US-Minnesota",
  "US-Mississippi",
  "US-Missouri",
  "US-Montana",
  "US-Nebraska",
  "US-Nevada",
  "US-New Hampshire",
  "US-New Jersey",
  "US-New Mexico",
  "US-New York",
  "US-North Carolina",
  "US-North Dakota",
  "US-Ohio",
  "US-Oklahoma",
  "US-Oregon",
  "US-Pennsylvania",
  "US-Rhode Island",
  "US-South Carolina",
  "US-South Dakota",
  "US-Tennessee",
  "US-Texas",
  "US-Utah",
  "US-Vermont",
  "US-Virginia",
  "US-Washington",
  "US-West Virginia",
  "US-Wisconsin",
  "US-Wyoming",
]

export const finlandSweden = [
  "Finland",
  "Sweden",
]

export const nordicsPlus = [
  "Finland",
  "Sweden",
  "Norway",
  "Denmark",
  "Iceland",
  "Switzerland",
]

export const europeanUnion = [
  "Austria",
  "Belgium",
  "Bulgaria",
  "Croatia",
  "Cyprus",
  "Czechia",
  "Denmark",
  "Estonia",
  "Finland",
  "France",
  "Germany",
  "Greece",
  "Hungary",
  "Ireland",
  "Italy",
  "Latvia",
  "Lithuania",
  "Luxembourg",
  "Malta",
  "Netherlands",
  "Poland",
  "Portugal",
  "Romania",
  "Slovakia",
  "Slovenia",
  "Spain",
  "Sweden",
]
